<?xml version="1.0" encoding="utf-8"?><Database Name="HOAA051_ngochua" Class="NgocHuaDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=112.78.2.84,1433;Initial Catalog=HOAA051_ngochua;Persist Security Info=True;User ID=HOAA051_ngochua" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HOAA051_ngochuaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHd" Member="ChiTietHds">
    <Type Name="ChiTietHd">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SingleAmt" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmt" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="HangHoaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoaDonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HangHoa_ChiTietHd" Member="HangHoa" ThisKey="HangHoaId" OtherKey="Id" Type="HangHoa" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHd" Member="HoaDon" ThisKey="HoaDonId" OtherKey="Id" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiKhoan_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="TaiKhoanId" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangHoa" Member="HangHoas">
    <Type Name="HangHoa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Stt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nhom" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SanXuat" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IsHot" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HangHoa_ChiTietHd" Member="ChiTietHds" ThisKey="Id" OtherKey="HangHoaId" Type="ChiTietHd" />
      <Association Name="HangHoa_HinhAnh" Member="HinhAnhs" ThisKey="Id" OtherKey="HangHoaId" Type="HinhAnh" />
    </Type>
  </Table>
  <Table Name="dbo.HinhAnh" Member="HinhAnhs">
    <Type Name="HinhAnh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HangHoaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HangHoa_HinhAnh" Member="HangHoa" ThisKey="HangHoaId" OtherKey="Id" Type="HangHoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TotalAmt" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XacNhan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TamThoi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_ChiTietHd" Member="ChiTietHds" ThisKey="Id" OtherKey="HoaDonId" Type="ChiTietHd" />
      <Association Name="TaiKhoan_HoaDon" Member="TaiKhoan" ThisKey="TaiKhoanId" OtherKey="Id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>